Repository DeveloperAcademy-POSTECH/2025-C4-M14-Graphicana, pull requests merged in 2025-07, with the labels that each got.

#8 design/#4 더미맵 바운더리 추가
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/DummyMapBoundary/250706_DummyMap_Sample.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/DummyMapBoundary/textures/color_121212.hdr
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Ttouch/Ttouch.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Ttouch/textures/color_121212.hdr
Labels: design

#19 feat: 조이스틱 UI 및 로직 구현 (패키지)
  Packages/ThumbStickView/Package.swift
  Packages/ThumbStickView/Sources/ThumbStickView/ThumbStickView.swift
  Project.swift
Labels: feat

#20 [Feat] 게임 내 카메라 기능 구현 (패키지)
  Packages/WorldCamera/Package.swift
  Packages/WorldCamera/README.md
  Packages/WorldCamera/Sources/WorldCamera/CameraLockAction.swift
  Packages/WorldCamera/Sources/WorldCamera/CameraOrientAction.swift
  Packages/WorldCamera/Sources/WorldCamera/FollowComponent.swift
  Packages/WorldCamera/Sources/WorldCamera/LockCameraComponent.swift
  Packages/WorldCamera/Sources/WorldCamera/WorldCameraComponent.swift
  Packages/WorldCamera/Sources/WorldCamera/WorldCameraSystem.swift
  Project.swift
Labels: feat

#22 [Feat] 게임 시작시 초기 화면 구현
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/ContentView.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/TtouchIslandApp.swift
Labels: feat

#25 [Feat] 게임 내 카메라 구현
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/jiwon.rcuserdata
  TtouchIsland/Sources/ControllerInput/GameView+Camera.swift
Labels: feat

#27 [Chore] GameView 네이밍 수정
  TtouchIsland/Sources/GameView+Camera.swift
  TtouchIsland/Sources/GameView.swift
Labels: chore

#42 [Fix] 캐릭터 이동 조이스틱 자연스럽게 수정
  TtouchIsland/Sources/ControllerInput/ControllerInputSystem.swift
Labels: bug

#44 desgin/#38 SkyBox추가 및 맵 수정 업데이트
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/ProjectData/main.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/EnvironmentMapV2/EnvironmentMap.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/EnvironmentMapV2/textures/Texture_01.png
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/EnvironmentMapV2/textures/color_121212.hdr
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Ocean/OceanPlane.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Ocean/textures/Texture_01.png
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Ocean/textures/color_121212.hdr
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/SkyBox.usda
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/SkySphere.usdz
Labels: design

#46 [Feat] 게임 플레이 중 재생될 오디오 구현
  TtouchIsland/Sources/GameView+Audio.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/background.wav
Labels: feat

#47 [Feat] 아이템과 가까워지면 버튼 생겨나기
  Packages/CharacterMovement/Sources/CharacterMovement/CharacterMovementComponent.swift
  Packages/ControllerInput/.gitignore
  Packages/ControllerInput/Package.swift
  Packages/ControllerInput/Sources/ControllerInput/ControllerInputReceiver.swift
  Packages/ControllerInput/Sources/ControllerInput/ControllerInputSystem.swift
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeongikim.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  Packages/ThumbStickView/Sources/ThumbStickView/ThumbStickView.swift
  Project.swift
  TtouchIsland/Resources/Audio/background.wav
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/CharacterComponent.swift
  TtouchIsland/Sources/ContentView.swift
  TtouchIsland/Sources/GameCollisionGroup.swift
  TtouchIsland/Sources/GameView+CharacterMovement.swift
  TtouchIsland/Sources/GameView+CharacterSetup.swift
  TtouchIsland/Sources/GameView+Item.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/ItemComponent.swift
  TtouchIsland/Sources/ItemSystem.swift
  TtouchIsland/Sources/TtouchIslandApp.swift
Labels: feat

#53 [Feat] 엔딩 도달 & 모든 아이템 수집시 바다 침몰 구현
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/jiwon.rcuserdata
  Packages/ThumbStickView/Sources/ThumbStickView/ThumbStickView.swift
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/ItemSystem.swift
Labels: feat

#62 [Feat] #40/#41 신문 자세히 보기 + 캐릭터 상태바 로직 구현
  Packages/WorldCamera/Sources/WorldCamera/CameraLockAction.swift
  Packages/WorldCamera/Sources/WorldCamera/CameraOrientAction.swift
  Packages/WorldCamera/Sources/WorldCamera/FollowComponent.swift
  Packages/WorldCamera/Sources/WorldCamera/WorldCameraComponent.swift
  TtouchIsland/Resources/Assets.xcassets/backpack.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/backpack.imageset/backpack.png
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/ContentView.swift
  TtouchIsland/Sources/GameStatusView.swift
  TtouchIsland/Sources/GameView+Camera.swift
  TtouchIsland/Sources/GameView+Item.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/ItemSystem.swift
Labels: feat

#66 design/#56 그림자 활성화
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  TtouchIsland/Sources/GameView.swift
Labels: design

#73 [Chore] StatusView 위치 조정 + 신문 볼때 로직 수정
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/ContentView.swift
  TtouchIsland/Sources/GameStatusView.swift
  TtouchIsland/Sources/GameView.swift
Labels: chore

#75 [Feat] #65 각 아이템들에 대한 상호작용 함수를 작성하기 위한 사전 코드
  TtouchIsland/Sources/GameView+Item.swift
  TtouchIsland/Sources/GameView.swift
  TtouchIsland/Sources/ItemComponent.swift
  TtouchIsland/Sources/ItemSystem.swift
Labels: feat

#78 [Hotfix] Gameview 컨플릭 잘못 해결한 부분 핫픽스
  Packages/WorldCamera/Sources/WorldCamera/WorldCameraComponent.swift
  TtouchIsland/Sources/GameView+Collision.swift
  TtouchIsland/Sources/GameView.swift
Labels: bug

#81 Design/#80 아이템 구분 효과 추가
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  TtouchIsland/Sources/GameView.swift
Labels: design

#82 [Feat+Refactor] 상단 Status창 Lottie + 로직 일부 적용 / 프로젝트 구조 정리
  .package.resolved
  Project.swift
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Backpack.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Backpack.imageset/ItemBag.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Backpack_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Backpack_Outline.imageset/ItemBagLine.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Bottle.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Bottle.imageset/ItemBottle.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Bottle_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Bottle_Outline.imageset/ItemBottleLine.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Cheese.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Cheese.imageset/ItemCheeze.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Cheese_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Cheese_Outline.imageset/ItemCheezeLine.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Flashlight.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Flashlight.imageset/ItemFlashlight.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Flashlight_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Flashlight_Outline.imageset/ItemFlashligntLine.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Map.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Map.imageset/ItemMap.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Map_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Map_Outline.imageset/ItemMapLine.svg
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Mystery_Outline.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/ItemUI/Mystery_Outline.imageset/QBoxLine.svg
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Basic.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Basic.dataset/TtouchMouse_Basic.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Happy.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Happy.dataset/TtouchMouse_Happy.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Jump.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Jump.dataset/TtouchMouse_Jump.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_News.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_News.dataset/TtouchMouse_News.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Run.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Run.dataset/TtouchMouse_Run.json
  TtouchIsland/Resources/Assets.xcassets/backpack.imageset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/backpack.imageset/backpack.png
  TtouchIsland/Sources/App/ContentView.swift
  TtouchIsland/Sources/App/TtouchIslandApp.swift
  TtouchIsland/Sources/AppModel.swift
  TtouchIsland/Sources/Character/CharacterComponent.swift
  TtouchIsland/Sources/Collision/GameCollisionGroup.swift
  TtouchIsland/Sources/Game/GameView+Camera.swift
  TtouchIsland/Sources/Game/GameView+CharacterMovement.swift
  TtouchIsland/Sources/Game/GameView+CharacterSetup.swift
  TtouchIsland/Sources/Game/GameView+Collision.swift
  TtouchIsland/Sources/Game/GameView+Item.swift
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/GameStatusView.swift
  TtouchIsland/Sources/Item/ItemComponent.swift
  TtouchIsland/Sources/Item/ItemSystem.swift
  TtouchIsland/Sources/Manager/AudioManager.swift
  TtouchIsland/Sources/Manager/GameManager.swift
  TtouchIsland/Sources/Shared/Component/StatusAnimationIcon.swift
  TtouchIsland/Sources/Shared/Component/StatusAnimationItems.swift
  TtouchIsland/Sources/Shared/Component/StatusItem.swift
  TtouchIsland/Sources/UI/GameStatusView.swift
Labels: feat, design, refactor

#85 feat: Cheese Item 인터렉션 구현 (땃쥐 크기 x2)
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Basic.dataset/TtouchMouse_Basic.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Happy.dataset/TtouchMouse_Happy.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Jump.dataset/TtouchMouse_Jump.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_News.dataset/TtouchMouse_News.json
  TtouchIsland/Resources/Assets.xcassets/LottiStatus/TtouchMouse_Run.dataset/TtouchMouse_Run.json
  TtouchIsland/Sources/Game/GameView+CharacterSetup.swift
  TtouchIsland/Sources/Game/GameView+Item.swift
  TtouchIsland/Sources/Game/GameView.swift
Labels: feat

#89 [Feat] 땃쥐 로티 애니메이션 정상화
  TtouchIsland/Sources/Game/GameView+Item.swift
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Manager/GameManager.swift
  TtouchIsland/Sources/Shared/Component/StatusAnimationIcon.swift
  TtouchIsland/Sources/Shared/Component/StatusAnimationItems.swift
  TtouchIsland/Sources/Shared/Enum/CharacterStatus.swift
  TtouchIsland/Sources/UI/GameStatusView.swift
Labels: feat

#92 [Feat] 런치 화면 구현
  TtouchIsland/Resources/Lottie/LoadingScreen.json
  TtouchIsland/Sources/App/ContentView.swift
  TtouchIsland/Sources/App/LaunchView.swift
  TtouchIsland/Sources/App/TtouchIslandApp.swift
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Manager/GameManager.swift
Labels: feat

#95 Design/#70 땃쥐 애니메이션 최신화
  Packages/CharacterMovement/Sources/CharacterMovement/CharacterStates.swift
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Items/Backpack_Anim.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/Ttouch.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/Ttouch_idle.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/Ttouch_walk.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/Ttouch_walk2.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/Ttouch_walk3.usd
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/textures/Texture_01.png
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/TtouchV3-1/textures/color_121212.hdr
  TtouchIsland/Sources/Game/GameView+CharacterSetup.swift
  TtouchIsland/Sources/Item/ItemSystem.swift
Labels: chore

#98 [Feat] 엔드 포인트 도달 후 애니메이션 & 다시하기 구현
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/jiwon.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Item/ItemSystem.swift
  TtouchIsland/Sources/Manager/GameManager.swift
Labels: feat

#103 fix/#101 Scene파일 수정
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene2.usda
  TtouchIsland/Sources/Game/GameView.swift
Labels: bug

#114 [Chore] showInterface 살리고 resetbutton 크기 및 패딩 조정
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Manager/ItemManager.swift
Labels: chore

#117 [Feat] #69 : 맵 아이템 인터렉션 구현
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Graphics/BloomEffect.swift
  TtouchIsland/Sources/Item/ItemSystem.swift
  TtouchIsland/Sources/Manager/ItemManager.swift
Labels: feat

#124 [Chore] 엔딩크레딧 에셋 갈아끼우기
  TtouchIsland/Resources/Lottie/EndCredits.json
  TtouchIsland/Resources/Lottie/EndcreditsLottie.json
  TtouchIsland/Resources/Lottie/LoadingScreen.json
  TtouchIsland/Sources/UI/EndCreditsView.swift
Labels: chore

#126 [Feat/#118] 각 아이템 획득 & 시도시 땃쥐 대화 로티 재생 구현
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeongikim.rcuserdata
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Bag.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Bag.dataset/Conversation_Bag.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Bottle.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Bottle.dataset/Conversation_Bottle.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Cheeze.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Cheeze.dataset/Conversation_Cheeze.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Flashlight.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Flashlight.dataset/Conversation_flashlight.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Map.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_Map.dataset/Conversation_Map.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_NeedBag.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_NeedBag.dataset/Conversation_NeedBag.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_NeedNewspaper.dataset/Contents.json
  TtouchIsland/Resources/Assets.xcassets/TtouchSpeech/Speech_NeedNewspaper.dataset/Conversation_NeedNewspaper.json
  TtouchIsland/Sources/Game/Character/CharacterComponent.swift
  TtouchIsland/Sources/Game/Collision/GameCollisionGroup.swift
  TtouchIsland/Sources/Game/GameView+Collision.swift
  TtouchIsland/Sources/Game/GameView.swift
  TtouchIsland/Sources/Game/Item/ItemComponent.swift
  TtouchIsland/Sources/Game/Item/ItemSystem.swift
  TtouchIsland/Sources/Game/Stage/StageComponent.swift
  TtouchIsland/Sources/Manager/GameManager.swift
  TtouchIsland/Sources/Manager/ItemManager.swift
  TtouchIsland/Sources/Shared/Component/CharacterSpeechBalloon.swift
  TtouchIsland/Sources/Shared/Component/StatusAnimationIcon.swift
  TtouchIsland/Sources/Shared/Enum/CharacterActStatus.swift
  TtouchIsland/Sources/Shared/Enum/CharacterSpeechStatus.swift
  TtouchIsland/Sources/UI/GameStatusView.swift
  TtouchIsland/Sources/UI/JoystickButtonView.swift
Labels: feat

#129 design/#125 아이템 위치 수정
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/B4863DCF-98C5-4234-80FE-5B9EFCAE5DAD/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/PluginData/BAEDFABF-64E5-4C1F-A476-9F3FDCF0BA77/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Packages/DummyAssets/Package.realitycomposerpro/WorkspaceData/hyeokcho.rcuserdata
  Packages/DummyAssets/Sources/DummyAssets/DummyAssets.rkassets/Scene.usda
Labels: chore
